name: Events exercices

on:
  push:
    branches:
      - "dev"
      - "main"
      - "feat/**"
      - "!staging"
    paths:
      - '**.ts'
      - 'src/**'
  pull_request:
    types:
      - closed
      - opened
  schedule:
    - cron: '*/5 * * * *'
    - cron: '30 */1 * * *'
    - cron: '00 3 * * 2'
  workflow_dispatch:

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)